// GitHub Pull Request Service

import { exec } from "child_process";
import { promisify } from "util";

const execAsync = promisify(exec);

export interface CreatePrParams {
  branchId: string;
  repository?: string;
  title?: string;
  body?: string;
}

export interface PrResult {
  url: string;
  number: number;
}

export class GitHubPrService {
  private token: string;

  constructor() {
    this.token = process.env.GITHUB_TOKEN || "";
    if (!this.token) {
      console.warn("[GitHubPrService] GITHUB_TOKEN not set, PR creation will fail");
    }
  }

  /**
   * Create a Pull Request from Ralph branch to dev
   */
  async createPrToDev(params: CreatePrParams): Promise<PrResult> {
    const { branchId, repository, title, body } = params;
    const branchName = `feature/ralph-${branchId}`;
    const repoName = repository || await this.getRepositoryName();

    // Create PR using GitHub CLI
    const prTitle = title || `Ralph: ${branchId}`;
    const prBody = body || this.generatePrBody(branchId);

    const command = [
      `gh pr create`,
      `--repo ${repoName}`,
      `--base dev`,
      `--head ${branchName}`,
      `--title "${prTitle}"`,
      `--body "${prBody}"`
    ].join(" ");

    const { stdout, stderr } = await execAsync(command, {
      env: { ...process.env, GH_TOKEN: this.token }
    });

    // Extract PR URL from output
    const urlMatch = stdout.match(/https:\/\/github\.com\/[^\/]+\/[^\/]+\/pull\/\d+/);
    if (!urlMatch) {
      throw new Error(`Failed to parse PR URL from gh output: ${stdout}\n${stderr}`);
    }

    // Extract PR number from URL
    const numberMatch = urlMatch[0].match(/\/pull\/(\d+)/);
    const prNumber = numberMatch ? parseInt(numberMatch[1]) : 0;

    console.log(`[GitHubPrService] Created PR: ${urlMatch[0]}`);

    return {
      url: urlMatch[0],
      number: prNumber
    };
  }

  /**
   * Check if a PR already exists for this branch
   */
  async prExists(branchId: string): Promise<boolean> {
    const branchName = `feature/ralph-${branchId}`;
    const repoName = await this.getRepositoryName();

    try {
      const command = `gh pr list --repo ${repoName} --head ${branchName} --json url --jq '. | length'`;
      const { stdout } = await execAsync(command, {
        env: { ...process.env, GH_TOKEN: this.token }
      });

      return parseInt(stdout.trim()) > 0;
    } catch (error) {
      console.error(`[GitHubPrService] Failed to check PR existence:`, error);
      return false;
    }
  }

  /**
   * Generate PR body with Ralph context
   */
  private generatePrBody(branchId: string): string {
    return `## Ralph Auto-Generated PR

Branch: \`feature/ralph-${branchId}\`

This PR was automatically created by Ralph (AI development assistant).

### Review Notes
- Review changes before merging to dev
- Test functionality as appropriate
- Delete branch after merge: \`git branch -D feature/ralph-${branchId}\`

---

_Generated by Seed Node Agent_
`;
  }

  /**
   * Get repository name from git remote
   */
  private async getRepositoryName(): Promise<string> {
    try {
      const { stdout: remoteUrl } = await execAsync(`git config --get remote.origin.url`);
      
      // Parse "git@github.com:owner/repo.git" or "https://github.com/owner/repo.git"
      const repoMatch = remoteUrl.match(/github\.com[\/:](.+)\.git/);
      const repository = repoMatch ? repoMatch[1] : null;
      
      if (!repository) {
        throw new Error("Could not parse repository name from remote URL");
      }

      return repository;
    } catch (error) {
      console.error("[GitHubPrService] Failed to get repository name:", error);
      throw new Error("GIT_REMOTE_NOT_FOUND");
    }
  }

  /**
   * Merge PR to dev (optional utility)
   */
  async mergePr(params: {
    prNumber: number;
    repository?: string;
    method?: "merge" | "squash" | "rebase";
  }): Promise<void> {
    const { prNumber, repository, method = "squash" } = params;
    const repoName = repository || await this.getRepositoryName();

    const command = `gh pr merge ${prNumber} --repo ${repoName} --${method} --delete-branch`;
    await execAsync(command, {
      env: { ...process.env, GH_TOKEN: this.token }
    });

    console.log(`[GitHubPrService] Merged PR #${prNumber}`);
  }
}
